### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by vedantmamgain** [sahilsk11/glide#7]
Would be great if you can open up the discussion tab for the repo.

**Comment by sahilsk11** [comment]
What would you like to use discussions for?

**Comment by vedantmamgain** [comment]
- Feature Suggestions if you're open to that .
- Feedback over UI

**Comment by sahilsk11** [comment]
It's best to leave feedback and feature suggestions on our feedback form [here](https://airtable.com/shr2dgrLZTvXliBD6).
